// This file is generated by src/scripts/build-seed-from-shop.ts
import {
  addDays,
  dateIsoJst,
  getJstDowIndex,
  parseCheckinDateJst,
} from "./date-utils";
import type {
  Area,
  Dow,
  HouseId,
  HouseInfo,
  PricingConfig,
} from "./nah-the-key.types";

export const HOUSE_TABLE: Record<HouseId, HouseInfo> = {
  RUSUTSU: {
    id: "RUSUTSU",
    displayName: "RUSUTSU",
    area: "RUSUTSU",
    capacity: {
      standard: null,
      max: 8,
      coSleepingMax: null,
    },
    baselinePerNightJpy: 4740000,
    baselineReason: "推定: 公式販売価格(年30泊 約11.85億円)を年12%相当で日割り",
    uncertainty: "High",
    officialUrl: "https://notahotel.com/exclusive/rusutsu",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/rusutsu_ogp.jpg",
  },
  SETOUCHI_360: {
    id: "SETOUCHI_360",
    displayName: "360",
    area: "SETOUCHI",
    capacity: {
      standard: null,
      max: 10,
      coSleepingMax: null,
    },
    baselinePerNightJpy: 1700000,
    baselineReason:
      "推定: 公式販売価格(1/36・年30泊 約4億円)と3ヴィラ内の広さ差から",
    uncertainty: "High",
    officialUrl: "https://notahotel.com/shop/setouchi",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/setouchi_ogp.v3.png",
  },
  SETOUCHI_270: {
    id: "SETOUCHI_270",
    displayName: "270",
    area: "SETOUCHI",
    capacity: {
      standard: null,
      max: 10,
      coSleepingMax: null,
    },
    baselinePerNightJpy: 1600000,
    baselineReason:
      "推定: 公式販売価格(1/36・年30泊 約4億円)と3ヴィラ内の広さ差から",
    uncertainty: "High",
    officialUrl: "https://notahotel.com/shop/setouchi",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/setouchi_ogp.v3.png",
  },
  SETOUCHI_180: {
    id: "SETOUCHI_180",
    displayName: "180",
    area: "SETOUCHI",
    capacity: {
      standard: null,
      max: 8,
      coSleepingMax: null,
    },
    baselinePerNightJpy: 1500000,
    baselineReason:
      "推定: 公式販売価格(1/36・年30泊 約4億円)と3ヴィラ内の広さ差から",
    uncertainty: "High",
    officialUrl: "https://notahotel.com/shop/setouchi",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/setouchi_ogp.v3.png",
  },
  EARTH_ISHIGAKI: {
    id: "EARTH_ISHIGAKI",
    displayName: "EARTH",
    area: "ISHIGAKI",
    capacity: {
      standard: null, // 標準定員は未公表のため null
      max: 10,
      coSleepingMax: 6, // 公称あり
    },
    baselinePerNightJpy: 1000000,
    baselineReason: "推定: フラッグシップ（面積/販売価格）から100万円/泊",
    uncertainty: "Med",
    officialUrl: "https://notahotel.com/shop/ishigaki/earth",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/properties/ishigaki-earth_ogp.png",
  },
  TOJI_MINAKAMI: {
    id: "TOJI_MINAKAMI",
    displayName: "TOJI",
    area: "MINAKAMI",
    capacity: {
      standard: 4,
      max: 8,
      coSleepingMax: 4,
    },
    baselinePerNightJpy: 400000,
    baselineReason: "公式LP: 定価¥400,000〜/1 night",
    uncertainty: "Low",
    officialUrl: "https://notahotel.com/shop/minakami/toji",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/minakami-toji_ogp.v2.jpg",
  },
  CLUB_SUITE_MIURA: {
    id: "CLUB_SUITE_MIURA",
    displayName: "CLUB SUITE",
    area: "MIURA",
    capacity: {
      standard: null,
      max: 4,
      coSleepingMax: null,
    },
    baselinePerNightJpy: 330000,
    baselineReason: "推定: 販売価格(年10泊)と青島層との相対比較 →33万円",
    uncertainty: "High",
    officialUrl: "https://notahotel.com/shop/miura/club-suite",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/properties/miura-club-suite.jpg",
  },
  BASE_L_KITA_KARUIZAWA: {
    id: "BASE_L_KITA_KARUIZAWA",
    displayName: "BASE MODEL L",
    area: "KITA_KARUIZAWA",
    capacity: {
      standard: 4,
      max: 8,
      coSleepingMax: 4,
    },
    baselinePerNightJpy: 280000,
    baselineReason: "公式アプリ: ¥280,000~/1 night",
    uncertainty: "Low",
    officialUrl: "https://notahotel.com/shop/kitakaruizawa/base-l",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/kitakaruizawa-base-l_ogp.v2.jpg",
  },
  NATURE_WITHIN_KITA_KARUIZAWA: {
    id: "NATURE_WITHIN_KITA_KARUIZAWA",
    displayName: "NATURE WITHIN",
    area: "KITA_KARUIZAWA",
    capacity: {
      standard: null,
      max: 8,
      coSleepingMax: null,
    },
    baselinePerNightJpy: 1050000,
    baselineReason: "推定: 公式販売価格(年10泊 約8,763万円)を年12%相当で日割り",
    uncertainty: "High",
    officialUrl: "https://notahotel.com/shop/kitakaruizawa/nature-within",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/nature-within_ogp.png",
  },
  COAST_AOSHIMA: {
    id: "COAST_AOSHIMA",
    displayName: "COAST",
    area: "AOSHIMA",
    capacity: {
      standard: null,
      max: 4,
      coSleepingMax: null,
    },
    baselinePerNightJpy: 300000,
    baselineReason: "推定: 販売価格と青島内の序列から →30万円",
    uncertainty: "Med",
    officialUrl: "https://notahotel.com/shop/aoshima/coast",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/aoshima-coast_ogp.jpg",
  },
  CLUB_VILLA_MIURA: {
    id: "CLUB_VILLA_MIURA",
    displayName: "CLUB VILLA",
    area: "MIURA",
    capacity: {
      standard: null,
      max: 8,
      coSleepingMax: null,
    },
    baselinePerNightJpy: 450000,
    baselineReason: "推定: 規模・プール付・販売価格から →45万円",
    uncertainty: "High",
    officialUrl: "https://notahotel.com/shop/miura/club-villa",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/properties/miura-club-villa.jpg",
  },
  MASU_KITA_KARUIZAWA: {
    id: "MASU_KITA_KARUIZAWA",
    displayName: "MASU",
    area: "KITA_KARUIZAWA",
    capacity: {
      standard: null,
      max: 6,
      coSleepingMax: null,
    },
    baselinePerNightJpy: 300000,
    baselineReason: "推定: 面積・仕様でBASE L/IRORIの中間 →30万円",
    uncertainty: "Med",
    officialUrl: "https://notahotel.com/shop/kitakaruizawa/masu",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/kitakaruizawa-masu_ogp.jpg",
  },
  CHILL_2_AOSHIMA: {
    id: "CHILL_2_AOSHIMA",
    displayName: "CHILL2.0",
    area: "AOSHIMA",
    capacity: {
      standard: null,
      max: 6,
      coSleepingMax: null,
    },
    baselinePerNightJpy: 400000,
    baselineReason: "推定: CHILL(35万)とMASTERPIECE(45万)の中間 →40万円",
    uncertainty: "Med",
    officialUrl: "https://notahotel.com/shop/aoshima/chill-2",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/aoshima-chill-2_ogp.jpg",
  },
  AOSHIMA_EXCLUSIVE: {
    id: "AOSHIMA_EXCLUSIVE",
    displayName: "MASTERPIECE",
    area: "AOSHIMA",
    capacity: {
      standard: 4,
      max: 8,
      coSleepingMax: 2,
    },
    baselinePerNightJpy: 450000,
    baselineReason: "公式アプリ: ¥450,000~/1 night",
    uncertainty: "Low",
    officialUrl: "https://notahotel.com/shop/aoshima/masterpiece",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/aoshima-masterpiece_ogp.jpg",
  },
  CHILL_AOSHIMA: {
    id: "CHILL_AOSHIMA",
    displayName: "CHILL",
    area: "AOSHIMA",
    capacity: {
      standard: 2,
      max: 4,
      coSleepingMax: 2,
    },
    baselinePerNightJpy: 350000,
    baselineReason: "公式アプリ: ¥350,000~/1 night",
    uncertainty: "Low",
    officialUrl: "https://notahotel.com/shop/aoshima/chill",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/aoshima-chill_ogp.jpg",
  },
  SURF_AOSHIMA: {
    id: "SURF_AOSHIMA",
    displayName: "SURF",
    area: "AOSHIMA",
    capacity: {
      standard: 2,
      max: 4,
      coSleepingMax: 2,
    },
    baselinePerNightJpy: 250000,
    baselineReason: "公式アプリ: ¥250,000~/1 night",
    uncertainty: "Low",
    officialUrl: "https://notahotel.com/shop/aoshima/surf",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/aoshima-surf_ogp.jpg",
  },
  GARDEN_AOSHIMA: {
    id: "GARDEN_AOSHIMA",
    displayName: "GARDEN",
    area: "AOSHIMA",
    capacity: {
      standard: 2,
      max: 4,
      coSleepingMax: 2,
    },
    baselinePerNightJpy: 150000,
    baselineReason: "公式アプリ: ¥150,000~/1 night",
    uncertainty: "Low",
    officialUrl: "https://notahotel.com/shop/aoshima/garden",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/aoshima-garden_ogp.jpg",
  },
  IRORI_KITA_KARUIZAWA: {
    id: "IRORI_KITA_KARUIZAWA",
    displayName: "IRORI",
    area: "KITA_KARUIZAWA",
    capacity: {
      standard: 4,
      max: 8,
      coSleepingMax: 4,
    },
    baselinePerNightJpy: 450000,
    baselineReason: "公式アプリ: ¥450,000~/1 night",
    uncertainty: "Low",
    officialUrl: "https://notahotel.com/shop/kitakaruizawa/irori",
    officialThumbUrl:
      // "https://notahotel.com/assets/images/ogp/shop/kitakaruizawa-irori_ogp.v2.jpg", // 404になるので下
      "https://images.microcms-assets.io/assets/1a905fa32d0e4bb1b2f280ab2ee5451d/6d5e5788559348718c20f66680eb50f9/irori_thumnail.png",
  },
  IRORI_2_KITA_KARUIZAWA: {
    id: "IRORI_2_KITA_KARUIZAWA",
    displayName: "IRORI 2.0",
    area: "KITA_KARUIZAWA",
    capacity: {
      standard: 4,
      max: 8,
      coSleepingMax: 4,
    },
    baselinePerNightJpy: 840000,
    baselineReason: "推定: 公式販売価格(年10泊 約6,994万円)を年12%相当で日割り",
    uncertainty: "High",
    officialUrl: "https://notahotel.com/shop/kitakaruizawa/irori-2",
    officialThumbUrl: "https://notahotel.com/assets/images/ogp/next/irori2.png",
  },
  BASE_M_KITA_KARUIZAWA: {
    id: "BASE_M_KITA_KARUIZAWA",
    displayName: "BASE MODEL M",
    area: "KITA_KARUIZAWA",
    capacity: {
      standard: 4,
      max: 4,
      coSleepingMax: 4,
    },
    baselinePerNightJpy: 180000,
    baselineReason: "推定: BASE S(約10万)とL(28万)の中間 →18万円",
    uncertainty: "Med",
    officialUrl: "https://notahotel.com/shop/kitakaruizawa/base-m",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/kitakaruizawa-base-m_ogp.v2.jpg",
  },
  BASE_S_KITA_KARUIZAWA: {
    id: "BASE_S_KITA_KARUIZAWA",
    displayName: "BASE MODEL S",
    area: "KITA_KARUIZAWA",
    capacity: {
      standard: 2,
      max: 2,
      coSleepingMax: 2,
    },
    baselinePerNightJpy: 100000,
    baselineReason: "公式アプリ: ¥99,999~/1 night（約10万円）",
    uncertainty: "Low",
    officialUrl: "https://notahotel.com/shop/kitakaruizawa/base-s",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/kitakaruizawa-base-s_ogp.v2.jpg",
  },
  MASTERPIECE_NASU: {
    id: "MASTERPIECE_NASU",
    displayName: "MASTERPIECE",
    area: "NASU",
    capacity: {
      standard: 4,
      max: 10,
      coSleepingMax: 4,
    },
    baselinePerNightJpy: 600000,
    baselineReason: "公式LP: 定価¥600,000〜/1 night",
    uncertainty: "Low",
    officialUrl: "https://notahotel.com/shop/nasu/masterpiece",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/nasu-masterpiece_ogp.jpg",
  },
  CAVE_NASU: {
    id: "CAVE_NASU",
    displayName: "CAVE",
    area: "NASU",
    capacity: {
      standard: 6,
      max: 6,
      coSleepingMax: null, // 公表なしのため null
    },
    baselinePerNightJpy: 500000,
    baselineReason: "公式LP: 定価¥500,000〜/1 night",
    uncertainty: "Low",
    officialUrl: "https://notahotel.com/shop/nasu/cave",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/nasu-cave_ogp.jpg",
  },
  THINK_NASU: {
    id: "THINK_NASU",
    displayName: "THINK",
    area: "NASU",
    capacity: {
      standard: 4,
      max: 4,
      coSleepingMax: 3,
    },
    baselinePerNightJpy: 500000,
    baselineReason: "公式アプリ: ¥500,000~/1 night",
    uncertainty: "Low",
    officialUrl: "https://notahotel.com/shop/nasu/think",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/nasu-think_ogp.jpg",
  },
  PENTHOUSE_FUKUOKA: {
    id: "PENTHOUSE_FUKUOKA",
    displayName: "+PENTHOUSE",
    area: "FUKUOKA",
    capacity: {
      standard: 4,
      max: 8,
      coSleepingMax: 2,
    },
    baselinePerNightJpy: 180000,
    baselineReason:
      "推定: 過去の公式アプリ¥180,000~/1 night（現公開ページは個別価格未掲載）",
    uncertainty: "Med",
    officialUrl: "https://notahotel.com/shop/fukuoka/penthouse",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/fukuoka-penthouse_ogp.jpg",
  },
  SOUND_FUKUOKA: {
    id: "SOUND_FUKUOKA",
    displayName: "+SOUND",
    area: "FUKUOKA",
    capacity: {
      standard: 4,
      max: 8,
      coSleepingMax: 2,
    },
    baselinePerNightJpy: 120000,
    baselineReason:
      "公式LP: FUKUOKA全体の定価¥120,000〜/1 night（個別タイプ価格未掲載）",
    uncertainty: "Med",
    officialUrl: "https://notahotel.com/shop/fukuoka/sound",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/fukuoka-sound_ogp.jpg",
  },
  BAR_FUKUOKA: {
    id: "BAR_FUKUOKA",
    displayName: "+BAR",
    area: "FUKUOKA",
    capacity: {
      standard: 4,
      max: 8,
      coSleepingMax: 2,
    },
    baselinePerNightJpy: 120000,
    baselineReason:
      "公式LP: FUKUOKA全体の定価¥120,000〜/1 night（個別タイプ価格未掲載）",
    uncertainty: "Med",
    officialUrl: "https://notahotel.com/shop/fukuoka/bar",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/fukuoka-bar_ogp.jpg",
  },
  CHEF_FUKUOKA: {
    id: "CHEF_FUKUOKA",
    displayName: "+CHEF",
    area: "FUKUOKA",
    capacity: {
      standard: 4,
      max: 8,
      coSleepingMax: 2,
    },
    baselinePerNightJpy: 120000,
    baselineReason:
      "公式LP: FUKUOKA全体の定価¥120,000〜/1 night（個別タイプ価格未掲載）",
    uncertainty: "Med",
    officialUrl: "https://notahotel.com/shop/fukuoka/chef",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/fukuoka-chef_ogp.jpg",
  },
  DESK_FUKUOKA: {
    id: "DESK_FUKUOKA",
    displayName: "+DESK",
    area: "FUKUOKA",
    capacity: {
      standard: 3,
      max: 8,
      coSleepingMax: 2,
    },
    baselinePerNightJpy: 120000,
    baselineReason:
      "公式LP: FUKUOKA全体の定価¥120,000〜/1 night（個別タイプ価格未掲載）",
    uncertainty: "Med",
    officialUrl: "https://notahotel.com/shop/fukuoka/desk",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/fukuoka-desk_ogp.jpg",
  },
  ATELIER_FUKUOKA: {
    id: "ATELIER_FUKUOKA",
    displayName: "+ATELIER",
    area: "FUKUOKA",
    capacity: {
      standard: 2,
      max: 8,
      coSleepingMax: 0,
    },
    baselinePerNightJpy: 120000,
    baselineReason:
      "公式LP: FUKUOKA全体の定価¥120,000〜/1 night（個別タイプ価格未掲載）",
    uncertainty: "Med",
    officialUrl: "https://notahotel.com/shop/fukuoka/atelier",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/fukuoka-atelier_ogp.jpg",
  },
  THE_NIGO_HOUSE_TOKYO: {
    id: "THE_NIGO_HOUSE_TOKYO",
    displayName: "THE NIGO HOUSE",
    area: "TOKYO",
    capacity: {
      standard: null,
      max: 12,
      coSleepingMax: null,
    },
    baselinePerNightJpy: 3840000,
    baselineReason: "推定: 公式販売価格(年30泊 約9.60億円)を年12%相当で日割り",
    uncertainty: "High",
    officialUrl: "https://notahotel.com/exclusive/tokyo",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/tokyo_ogp.jpg",
  },
  RETREAT_FUKUOKA: {
    id: "RETREAT_FUKUOKA",
    displayName: "RETREAT",
    area: "FUKUOKA",
    capacity: {
      standard: 4,
      max: 8,
      coSleepingMax: 2,
    },
    baselinePerNightJpy: 120000,
    baselineReason:
      "公式LP: FUKUOKA全体の定価¥120,000〜/1 night（個別タイプ価格未掲載）",
    uncertainty: "Med",
    officialUrl: "https://notahotel.com/shop/fukuoka/retreat",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/fukuoka-retreat_ogp.jpg",
  },
  DOMA_FUKUOKA: {
    id: "DOMA_FUKUOKA",
    displayName: "DOMA",
    area: "FUKUOKA",
    capacity: {
      standard: 4,
      max: 8,
      coSleepingMax: 2,
    },
    baselinePerNightJpy: 120000,
    baselineReason:
      "公式LP: FUKUOKA全体の定価¥120,000〜/1 night（個別タイプ価格未掲載）",
    uncertainty: "Med",
    officialUrl: "https://notahotel.com/shop/fukuoka/doma",
    officialThumbUrl:
      "https://notahotel.com/assets/images/ogp/shop/fukuoka-doma_ogp.jpg",
  },
} as const;

// ===================== 需要係数 =====================
// ここに書くのは「相対的な需要の形」。絶対水準は正規化で決める。
//
// baseline は公式の「¥xxx,xxx〜/1 night」＝**年内で最も安い1泊**なので、
// 係数は 1.0 を下回ってはいけない（下回ると公表最安値より安い「公正価格」が出る）。
// そこで下の SHAPE を「最小値 = 1.0」になるよう機械的に正規化して使う。
// SHAPE を編集しても不変条件は自動的に保たれる。

const MONTH_DEMAND_SHAPE: Record<Area, Record<string, number>> = {
  AOSHIMA: {
    "1": 0.95,
    "2": 0.95,
    "3": 1.0,
    "4": 1.05,
    "5": 1.15, // GW
    "6": 0.95, // 梅雨
    "7": 1.2,
    "8": 1.25,
    "9": 1.05,
    "10": 1.05,
    "11": 1.0,
    "12": 0.95,
  },
  FUKUOKA: {
    "1": 1.0,
    "2": 0.95,
    "3": 0.95,
    "4": 1.0,
    "5": 1.1,
    "6": 0.95, // 梅雨
    "7": 1.1,
    "8": 1.15,
    "9": 1.05,
    "10": 1.05,
    "11": 1.0,
    "12": 0.95,
  },
  KITA_KARUIZAWA: {
    "1": 0.9,
    "2": 0.9,
    "3": 0.95,
    "4": 1.05,
    "5": 1.15, // GW
    "6": 0.95, // 梅雨で抑えめ
    "7": 1.3,
    "8": 1.35,
    "9": 1.1,
    "10": 1.05,
    "11": 1.0,
    "12": 0.95,
  },
  NASU: {
    "1": 0.95,
    "2": 0.9,
    "3": 0.95,
    "4": 1.05,
    "5": 1.15,
    "6": 0.95,
    "7": 1.2,
    "8": 1.25,
    "9": 1.1,
    "10": 1.15,
    "11": 1.05,
    "12": 1.0,
  },
  MIURA: {
    "1": 0.95,
    "2": 0.95,
    "3": 1.05,
    "4": 1.1,
    "5": 1.15,
    "6": 0.95,
    "7": 1.2,
    "8": 1.25,
    "9": 1.1,
    "10": 1.05,
    "11": 1.0,
    "12": 1.0,
  },
  MINAKAMI: {
    "1": 1.15,
    "2": 1.1,
    "3": 1.0,
    "4": 0.95,
    "5": 1.1,
    "6": 0.95,
    "7": 1.15,
    "8": 1.2,
    "9": 1.05,
    "10": 1.15,
    "11": 1.05,
    "12": 1.15,
  },
  SETOUCHI: {
    "1": 0.9,
    "2": 0.9,
    "3": 1.05,
    "4": 1.1,
    "5": 1.15, // GW
    "6": 0.95, // 梅雨
    "7": 1.1,
    "8": 1.2,
    "9": 1.1,
    "10": 1.15,
    "11": 1.05,
    "12": 1.0,
  },
  ISHIGAKI: {
    "1": 0.85,
    "2": 0.9,
    "3": 1.0,
    "4": 1.05,
    "5": 0.9, // 梅雨入り早め
    "6": 0.85, // 梅雨本番
    "7": 1.35, // ハイサマー
    "8": 1.35,
    "9": 1.05, // 台風リスクでやや抑え
    "10": 1.05,
    "11": 0.95,
    "12": 0.9,
  },
  TOKYO: {
    "1": 1.05, // 正月・初売り〜
    "2": 1.0,
    "3": 1.1, // 送別/卒業旅行
    "4": 1.15, // 新年度
    "5": 1.2, // GW
    "6": 1.0,
    "7": 1.05,
    "8": 1.05, // お盆
    "9": 1.05,
    "10": 1.1,
    "11": 1.1,
    "12": 1.2, // Xmas〜年末年始
  },
  RUSUTSU: {
    "1": 1.4, // パウダー最盛
    "2": 1.4,
    "3": 1.2,
    "4": 0.9,
    "5": 0.9,
    "6": 0.95,
    "7": 1.05,
    "8": 1.05,
    "9": 1.05,
    "10": 1.1, // 紅葉・秋旅
    "11": 1.2, // 初雪〜
    "12": 1.3, // スキー開幕
  },
};

const DOW_DEMAND_SHAPE: Record<Dow, number> = {
  Mon: 0.9,
  Tue: 0.9,
  Wed: 1.0,
  Thu: 1.0,
  Fri: 1.15,
  Sat: 1.25,
  Sun: 0.95,
};

/** 最小値がちょうど 1.0 になるよう全体をスケールする（相対的な形は保たれる） */
function normalizeToMinOne<K extends string>(
  shape: Record<K, number>,
): Record<K, number> {
  const values = Object.values(shape) as number[];
  const min = Math.min(...values);
  const out = {} as Record<K, number>;
  for (const [k, v] of Object.entries(shape) as Array<[K, number]>) {
    // 浮動小数の誤差で 0.9999… にならないよう 6 桁で丸める
    out[k] = Math.round(((v as number) / min) * 1e6) / 1e6;
  }
  return out;
}

/**
 * 日本の祝日（内閣府「国民の祝日」に基づく。振替休日を含む）。
 * 春分/秋分は年により前後するため、表に載っている年の分だけを扱い、
 * 範囲外の年は「祝日なし」として静かにフォールバックする（割増が乗らないだけ）。
 */
const JP_HOLIDAYS: string[] = [
  // 2026
  "2026-01-01",
  "2026-01-12",
  "2026-02-11",
  "2026-02-23",
  "2026-03-20",
  "2026-04-29",
  "2026-05-03",
  "2026-05-04",
  "2026-05-05",
  "2026-05-06",
  "2026-07-20",
  "2026-08-11",
  "2026-09-21",
  "2026-09-22",
  "2026-09-23",
  "2026-10-12",
  "2026-11-03",
  "2026-11-23",
  // 2027
  "2027-01-01",
  "2027-01-11",
  "2027-02-11",
  "2027-02-23",
  "2027-03-21",
  "2027-03-22",
  "2027-04-29",
  "2027-05-03",
  "2027-05-04",
  "2027-05-05",
  "2027-07-19",
  "2027-08-11",
  "2027-09-20",
  "2027-09-23",
  "2027-10-11",
  "2027-11-03",
  "2027-11-23",
  // 2028
  "2028-01-01",
  "2028-01-10",
  "2028-02-11",
  "2028-02-23",
  "2028-03-20",
  "2028-04-29",
  "2028-05-03",
  "2028-05-04",
  "2028-05-05",
  "2028-07-17",
  "2028-08-11",
  "2028-09-18",
  "2028-09-22",
  "2028-10-09",
  "2028-11-03",
  "2028-11-23",
];

export const DEFAULT_PRICING_CONFIG: PricingConfig = {
  // ethJpy は既定値を持たない。取得できなければ実効単価を出さない。
  monthFactor: Object.fromEntries(
    Object.entries(MONTH_DEMAND_SHAPE).map(([area, months]) => [
      area,
      normalizeToMinOne(months),
    ]),
  ),
  dowFactor: normalizeToMinOne(DOW_DEMAND_SHAPE),

  specialDay: {
    // 月係数では平準化されて消えてしまう、価格が最も跳ねる数日。
    ranges: [
      {
        id: "new-year",
        label: "年末年始",
        fromMmDd: "12-28",
        toMmDd: "01-03",
        factor: 1.6,
      },
      {
        id: "golden-week",
        label: "GW",
        fromMmDd: "04-29",
        toMmDd: "05-05",
        factor: 1.4,
      },
      {
        id: "obon",
        label: "お盆",
        fromMmDd: "08-11",
        toMmDd: "08-16",
        factor: 1.35,
      },
    ],
    holidays: JP_HOLIDAYS,
    holidayFactor: 1.1,
    holidayEveFactor: 1.25,
  },

  longStayFactor: {
    "1": 1.0,
    "2": 0.95,
    "3": 0.9,
    "7": 0.85,
    "14": 0.8,
  },

  leadtimeMargin: [
    { daysLt: 7, margin: 0.2 },
    { daysLt: 14, margin: 0.1 },
    { daysLt: 30, margin: 0.05 },
  ],

  baselineRelError: {
    Low: 0.1,
    Med: 0.25,
    High: 0.5,
  },
};

function mmDd(iso: string): string {
  return iso.slice(5, 10);
}

function inMmDdRange(target: string, from: string, to: string): boolean {
  // 年をまたぐレンジ（12-28 〜 01-03）は 2 区間に分けて判定する
  if (from <= to) return target >= from && target <= to;
  return target >= from || target <= to;
}

/**
 * 年末年始・GW・お盆・連休といった特異日の割増係数。
 * 必ず 1.0 以上を返す（baseline = 年内最安 という定義を壊さないため）。
 * 複数の条件に当たる場合は掛け合わせず最大値を採る。
 */
export function resolveSpecialDayFactor(
  dateIso: string,
  cfg: PricingConfig = DEFAULT_PRICING_CONFIG,
): number {
  const candidates: number[] = [1];
  const md = mmDd(dateIso);

  for (const range of cfg.specialDay.ranges) {
    if (inMmDdRange(md, range.fromMmDd, range.toMmDd)) {
      candidates.push(range.factor);
    }
  }

  const holidays = new Set(cfg.specialDay.holidays);
  const d = parseCheckinDateJst(dateIso);
  if (d) {
    const dow = getJstDowIndex(d); // 0=Sun
    const isWeekday = dow >= 1 && dow <= 5;
    if (isWeekday && holidays.has(dateIso)) {
      candidates.push(cfg.specialDay.holidayFactor);
    }
    // 翌日が祝日の夜は連休の入り口。土曜は曜日係数で既に上がるので除く。
    const tomorrow = dateIsoJst(addDays(d, 1));
    if (dow !== 6 && holidays.has(tomorrow)) {
      candidates.push(cfg.specialDay.holidayEveFactor);
    }
  }

  return Math.max(...candidates);
}

/** チェックイン日までの残日数から、上限入札に上乗せする安全マージンを返す */
export function resolveLeadtimeMargin(
  daysUntil: number | undefined,
  cfg: PricingConfig = DEFAULT_PRICING_CONFIG,
): number {
  if (daysUntil === undefined) return 0;
  const sorted = [...cfg.leadtimeMargin].sort((a, b) => a.daysLt - b.daysLt);
  for (const item of sorted) {
    if (daysUntil < item.daysLt) return item.margin;
  }
  return 0;
}

// ===== helper: 公式ページからOG画像を解決 =====
export async function resolveOgImage(url: string): Promise<string | undefined> {
  const res = await fetch(url, {
    headers: { "User-Agent": "Mozilla/5.0 (+https://github.com/whatwg/fetch)" },
  });
  const html = await res.text();
  const m =
    html.match(
      /<meta[^>]+property=["']og:image["'][^>]+content=["']([^"]+)["']/i,
    ) ||
    html.match(
      /<meta[^>]+name=["']twitter:image["'][^>]+content=["']([^"]+)["']/i,
    );
  return m?.[1];
}

/** サムネ未設定の項目にOG画像URLを流し込む */
export async function hydrateThumbnails(
  table: Record<HouseId, HouseInfo> = HOUSE_TABLE,
) {
  const ids = Object.keys(table) as HouseId[];
  for (const id of ids) {
    const item = table[id];
    if (!item.officialThumbUrl) {
      try {
        const og = await resolveOgImage(item.officialUrl);
        if (og) item.officialThumbUrl = og;
      } catch {
        // ignore
      }
    }
  }
  return table;
}
